import ImageTile from "@/components/ImageTile";
import Nav from "@/components/Nav";
import Head from "next/head";
import { useState } from "react";

const Favorites = () => {
const [favImages, setFavImages] = useState([])

  return (
    <>
      <Head>
        <title>Pic Pikk&uuml;r</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className='flex-col w-full items-center justify-center'>
        <h1 className='text-7xl font-bold text-center my-20' >Favorites</h1>
        {favImages.length ? favImages.map(image=>{
          return <ImageTile key={image.id} image={image} />
        })
        :
        <p className="text-center">Select your favorite images!</p>
        }
      </main>
    </>
  )
};

export default Favorites;
