import Head from 'next/head'
import Content from '@/components/Content'

export default function Home() {

  return (
    <>
      <Head>
        <title>Pic Pikkür</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className='text-4xl font-bold' >Welcome to Pic Pikkur</h1>
        <Content />
      </main>
    </>
  )
};
