import Head from 'next/head'
import Content from '@/components/Content'

export default function Home() {

  return (
    <>
      <Head>
        <title>Pic Pikk&uuml;r</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex-col w-full items-center justify-center'>
        <h1 className='text-4xl font-bold text-center' >Welcome to Pic Pikk&uuml;r</h1>
        <Content />
      </main>
    </>
  )
};
